---
apiVersion: v1
kind: Service
metadata:
   name: {{ .Values.deploymentName }}
   labels:
     app: {{ .Values.appName }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.containerPort }}
      protocol: TCP
      targetPort: {{ .Values.ports.containerPort }}
  selector:
    app: {{ .Values.appName }}