variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
    - test
    - build
    - release
include:
    - template: Security/SAST.gitlab-ci.yml

sonarqube-frontend-sast:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - cd frontend
    - "sonar-scanner \
      -Dsonar.projectKey=${SONAR_PROJECT_KEY_FRONT}
      -Dsonar.sources=. \
      -Dsonar.host.url=${SONAR_URL} \
      -Dsonar.login=${SONAR_LOGIN_FRONT}"    

build-frontend-artifact:
    stage: build
    cache:
      key: ${CI_COMMIT_REF_NAME}-FRONT-${VERSION}
      paths:
      - frontend/dist
    script:
        - cd frontend
        - npm install
        - export NODE_ENV=production
        - export VUE_APP_API_URL=http://localhost:8081
        - npm run build
    artifacts:
        paths:
          - $CI_PROJECT_DIR/frontend/dist
    needs:
      - sonarqube-frontend-sast

build-frontend-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/frontend"
      --dockerfile "${CI_PROJECT_DIR}/frontend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/diplom-frontend:${CI_COMMIT_SHORT_SHA}"
      --destination "${CI_REGISTRY_IMAGE}/diplom-frontend:latest"
      --build-arg VERSION=$VERSION
      --cache=true

upload-frontend-package:
    stage: release
    only:
        changes:
            - frontend/**/*
    needs:
        - build-frontend-artifact
    script:
        - cd $CI_PROJECT_DIR/frontend && ls -lah
        - tar czvf diplom-frontend-${VERSION}.tar.gz dist
        - >
            curl -v -u "${NEXUS_REPO_USER}:${NEXUS_REPO_PASS}"
            --upload-file diplom-frontend-${VERSION}.tar.gz
            ${NEXUS_FRONT}/${VERSION}/diplom-frontend-${VERSION}.tar.gz