image:
  repository: gitlab.praktikum-services.ru:5050/std-024-27/diploma/diplom-backend
  tag: latest
replicas: 1
resources:
  limits:
    memory: "500Mi"
    cpu: "0.2"
  requests:
    memory: "200Mi"
    cpu: "0.2"
ports:
  containerPort: 8081
secretName: backend-secrets
deploymentName: backend
appName: backend
